### PR TITLE
Add option to disable scrolling on page load

### PR DESCRIPTION
**Pull request by astorije**
This is following discussion in #32. Minified version built with Packer as mentioned in the thread.

I know you were not in favor of an option for this, but I had to come up with this for my own consumption until this is doable with the upstream version of the library (to be able to replace [my outdated copy](https://github.com/astorije/jeremie.astori.fr/blob/b69664c89405cae4842999748d73e66b0c23d86b/public_html/js/jquery.localscroll.min.js) while keeping the existing behavior). I figured I would make my changes available if anyone is interested as well in the future.

I would prefer not to monkey-patch a fork but I totally understand and respect your preferences, I did not intend to make a push for this PR to be merged. Feel free to close it or suggest improvements regardless of your decision 😃
Thanks!

### CODE REVIEW

**Comment by astorije** [comment]
@flesler, any chance you would consider this feature for `jquery.localScroll`?

To illustrate the change, if someone is interested, this is the issue I was facing, try the [before](https://5984f6bf424ef27ac22da94e--jeremie-astori-fr.netlify.com/resume.html#skills) / [after](https://5984f8f1a700c442544e31ce--jeremie-astori-fr.netlify.com/resume.html#skills) versions. In both cases, open and refresh the page. The before version will cause an animated scroll on load, while the after version will not (the before version also does not move to the right position on load, but that might be different).

At the moment, I'm [pointing to my own branch in `package.json`](https://github.com/astorije/jeremie.astori.fr/blob/master/package.json#L7), but I would rather help improving the upstream package, get rid of this silly line in `package.json` (git locations with npm do not work perfectly on top of that), and give the package download count back to you 😅.

Let me know if there is anything I can do to help :)

**Comment by flesler** [comment]
@astorije just 3 small changes:
- rename `load` to `autoscroll`. I like that you followed the short-single-word name but `load` is really ambiguous.
- Remove the trailing comma at the end of the options. I know it's now standard to add them and I do myself but I don't want re-test linting or have people complain because in their env it fails. Let's just follow the same standard.
- Don't update the minified version. I'll still do it myself afterwards (to ensure integrity) along with bumping the version.

Thanks!

**Comment by astorije** [comment]
@flesler, all 3 are done!
Re: minified version, I had used the exact same tool and settings than you for consistency and integrity, so you could see the diff was only my stuff. But totally understand, I removed the changes, just wanted to bring that up.

Also, a few things I noticed, in case that's helpful to you and your contributors/users:

- You have a bunch of trailing whitespaces in `jquery.locallScroll.js`, making things difficult for devs having an editor that trims trailing whitespaces everywhere by default (like Atom) :)
  I can easily fix that if you want, it's only a matter of saving the file for me!

- There is no newline at end of file for `jquery.locallScroll.min.js`. I realize it's the minifier that did that, but again with certain editors (like Atom, vim, nano...) that add one or won't let you not add one, it's kind of a (nitpicky) annoyance.

- As mentioned in [this comment](https://github.com/flesler/jquery.localScroll/issues/32#issuecomment-302829416), I found that you could save almost 10% on size by changing minifier. No big deal though.

Of course, feel free to ignore any of those, I simply figured that while I was here, I would report some observations :)

**Comment by flesler** [comment]
@astorije the code is old. I now use VS Code and it surely trims lines and adds one at the end. I'll do it when I bump if you haven't, don't worry.

About minification, nice finding. They seem to use Uglify. I'll switch to jscompress for this and future releases, thanks!

**Comment by flesler** [comment]
Done, added some misc tweaks and published `1.5.0` 👍

**Comment by astorije** [comment]
Yay, awesome, thank you very much, @flesler!!

**Pull request merged**
