### PR TITLE
require jQuery as a peerDependency

### PR DESCRIPTION
**Pull request by graingert**
You should load your host jQuery as a peerDependency: https://nodejs.org/en/blog/npm/peer-dependencies/#the-problem-plugins

### CODE REVIEW

**Comment by graingert** [comment]
otherwise I have my version of jQuery loaded into the page, and your plugin gets a different version

**Comment by graingert** [comment]
@flesler this should also help with #28

**Comment by astorije** [comment]
@flesler, are you planning to get this in? As far as I understand, it would be a sensible thing, no?

**Comment by flesler** [comment]
As I commented on the other ticket

>I'm not sure of the consequences of making that change on existing setups

I'm very hesitant to make this kind of changes

**Comment by astorije** [comment]
Oh, sorry, I didn't see that comment of yours.

In general, it's a good idea to require main project to be present when developing a plugin, see [`chai-as-promised`](https://github.com/domenic/chai-as-promised/blob/e237fd24a47924c6a625df7bbde2ae40783f7c6f/package.json#L31-L33) or (shameless plug) [`chai-immutable`](https://github.com/astorije/chai-immutable/blob/master/package.json#L39-L41) for example.

But I get what you're saying though, and maybe you'd be more comfortable keeping this for a 2.0.0 version bump.
In terms of consequences however, what this will do is `npm install` will fail if someone adds `jquery.localscroll` to their `package.json` without `jquery` or `jquery.scrollto` in it. In practice, people using your plugin outside of npm will not be affected, and I'm tempted to say that people using npm for it already have (need, even) these 2 packages in there. What's convenient for you is that you can start specifying which version of them it works with or not.

Do you know any setup/reason I might be ignoring that someone would use this plugin without `jquery` or `jquery.scrollto`? Only reason I can think of is if they have some weird setup where your 2 plugins are present, but jQuery itself comes from another source.

Either way, thanks for your answer!

**Comment by flesler** [comment]
@astorije I see, thanks for the explanation. We could indeed make it a major release and see how it goes

**Comment by flesler** [comment]
Bumped, tagged and published. Thank you 👍

**Pull request merged**
